/**
 * Indian cities for location-based SEO (Layer 3).
 * Slug is URL-friendly; name is for display.
 */

export interface Location {
  slug: string;
  name: string;
}

/** Major cities - Tier 1 & 2 (200+) */
export const CITIES: Location[] = [
  { slug: 'delhi', name: 'Delhi' },
  { slug: 'mumbai', name: 'Mumbai' },
  { slug: 'bangalore', name: 'Bangalore' },
  { slug: 'hyderabad', name: 'Hyderabad' },
  { slug: 'chennai', name: 'Chennai' },
  { slug: 'kolkata', name: 'Kolkata' },
  { slug: 'pune', name: 'Pune' },
  { slug: 'ahmedabad', name: 'Ahmedabad' },
  { slug: 'jaipur', name: 'Jaipur' },
  { slug: 'surat', name: 'Surat' },
  { slug: 'lucknow', name: 'Lucknow' },
  { slug: 'kanpur', name: 'Kanpur' },
  { slug: 'nagpur', name: 'Nagpur' },
  { slug: 'indore', name: 'Indore' },
  { slug: 'thane', name: 'Thane' },
  { slug: 'bhopal', name: 'Bhopal' },
  { slug: 'visakhapatnam', name: 'Visakhapatnam' },
  { slug: 'patna', name: 'Patna' },
  { slug: 'vadodara', name: 'Vadodara' },
  { slug: 'ghaziabad', name: 'Ghaziabad' },
  { slug: 'ludhiana', name: 'Ludhiana' },
  { slug: 'agra', name: 'Agra' },
  { slug: 'nashik', name: 'Nashik' },
  { slug: 'faridabad', name: 'Faridabad' },
  { slug: 'meerut', name: 'Meerut' },
  { slug: 'rajkot', name: 'Rajkot' },
  { slug: 'varanasi', name: 'Varanasi' },
  { slug: 'srinagar', name: 'Srinagar' },
  { slug: 'aurangabad', name: 'Aurangabad' },
  { slug: 'dhanbad', name: 'Dhanbad' },
  { slug: 'amritsar', name: 'Amritsar' },
  { slug: 'allahabad', name: 'Allahabad' },
  { slug: 'ranchi', name: 'Ranchi' },
  { slug: 'howrah', name: 'Howrah' },
  { slug: 'coimbatore', name: 'Coimbatore' },
  { slug: 'jabalpur', name: 'Jabalpur' },
  { slug: 'gwalior', name: 'Gwalior' },
  { slug: 'vijayawada', name: 'Vijayawada' },
  { slug: 'jodhpur', name: 'Jodhpur' },
  { slug: 'madurai', name: 'Madurai' },
  { slug: 'raipur', name: 'Raipur' },
  { slug: 'kota', name: 'Kota' },
  { slug: 'guwahati', name: 'Guwahati' },
  { slug: 'chandigarh', name: 'Chandigarh' },
  { slug: 'solapur', name: 'Solapur' },
  { slug: 'hubli', name: 'Hubli' },
  { slug: 'dharwad', name: 'Dharwad' },
  { slug: 'bareilly', name: 'Bareilly' },
  { slug: 'moradabad', name: 'Moradabad' },
  { slug: 'mysore', name: 'Mysore' },
  { slug: 'gurgaon', name: 'Gurgaon' },
  { slug: 'noida', name: 'Noida' },
  { slug: 'greater-noida', name: 'Greater Noida' },
  { slug: 'kochi', name: 'Kochi' },
  { slug: 'trivandrum', name: 'Thiruvananthapuram' },
  { slug: 'bhubaneswar', name: 'Bhubaneswar' },
  { slug: 'dehradun', name: 'Dehradun' },
  { slug: 'shimla', name: 'Shimla' },
  { slug: 'siliguri', name: 'Siliguri' },
  { slug: 'tiruchirappalli', name: 'Tiruchirappalli' },
  { slug: 'warangal', name: 'Warangal' },
  { slug: 'salem', name: 'Salem' },
  { slug: 'tirunelveli', name: 'Tirunelveli' },
  { slug: 'mira-bhayandar', name: 'Mira-Bhayandar' },
  { slug: 'thiruvananthapuram', name: 'Thiruvananthapuram' },
  { slug: 'bhiwandi', name: 'Bhiwandi' },
  { slug: 'saharanpur', name: 'Saharanpur' },
  { slug: 'mangalore', name: 'Mangalore' },
  { slug: 'belgaum', name: 'Belgaum' },
  { slug: 'ambarnath', name: 'Ambarnath' },
  { slug: 'tirupati', name: 'Tirupati' },
  { slug: 'malegaon', name: 'Malegaon' },
  { slug: 'gaya', name: 'Gaya' },
  { slug: 'jalandhar', name: 'Jalandhar' },
  { slug: 'tiruppur', name: 'Tiruppur' },
  { slug: 'davanagere', name: 'Davanagere' },
  { slug: 'kozhikode', name: 'Kozhikode' },
  { slug: 'akola', name: 'Akola' },
  { slug: 'kurnool', name: 'Kurnool' },
  { slug: 'ujjain', name: 'Ujjain' },
  { slug: 'raigarh', name: 'Raigarh' },
  { slug: 'tumkur', name: 'Tumkur' },
  { slug: 'dibrugarh', name: 'Dibrugarh' },
  { slug: 'jamshedpur', name: 'Jamshedpur' },
  { slug: 'bhatinda', name: 'Bathinda' },
  { slug: 'latur', name: 'Latur' },
  { slug: 'hospet', name: 'Hospet' },
  { slug: 'bellary', name: 'Ballari' },
  { slug: 'pimpri-chinchwad', name: 'Pimpri-Chinchwad' },
  { slug: 'panipat', name: 'Panipat' },
  { slug: 'cuttack', name: 'Cuttack' },
  { slug: 'rourkela', name: 'Rourkela' },
  { slug: 'jamnagar', name: 'Jamnagar' },
  { slug: 'bikaner', name: 'Bikaner' },
  { slug: 'udaipur', name: 'Udaipur' },
  { slug: 'ajmer', name: 'Ajmer' },
  { slug: 'bhilwara', name: 'Bhilwara' },
  { slug: 'erode', name: 'Erode' },
  { slug: 'vellore', name: 'Vellore' },
  { slug: 'tiruvannamalai', name: 'Tiruvannamalai' },
  { slug: 'nellore', name: 'Nellore' },
  { slug: 'kakinada', name: 'Kakinada' },
  { slug: 'guntur', name: 'Guntur' },
  { slug: 'kadapa', name: 'Kadapa' },
  { slug: 'anantapur', name: 'Anantapur' },
  { slug: 'nizamabad', name: 'Nizamabad' },
  { slug: 'karimnagar', name: 'Karimnagar' },
  { slug: 'secunderabad', name: 'Secunderabad' },

  // --- TELANGANA: All 33 districts & major cities ---
  { slug: 'adilabad', name: 'Adilabad' },
  { slug: 'asifabad', name: 'Asifabad' },
  { slug: 'mancherial', name: 'Mancherial' },
  { slug: 'nirmal', name: 'Nirmal' },
  { slug: 'jagtial', name: 'Jagtial' },
  { slug: 'peddapalli', name: 'Peddapalli' },
  { slug: 'kamareddy', name: 'Kamareddy' },
  { slug: 'sircilla', name: 'Sircilla' },
  { slug: 'bhupalpally', name: 'Bhupalpally' },
  { slug: 'sangareddy', name: 'Sangareddy' },
  { slug: 'medak', name: 'Medak' },
  { slug: 'siddipet', name: 'Siddipet' },
  { slug: 'jangaon', name: 'Jangaon' },
  { slug: 'hanumakonda', name: 'Hanumakonda' },
  { slug: 'mulugu', name: 'Mulugu' },
  { slug: 'kothagudem', name: 'Kothagudem' },
  { slug: 'khammam', name: 'Khammam' },
  { slug: 'mahabubabad', name: 'Mahabubabad' },
  { slug: 'suryapet', name: 'Suryapet' },
  { slug: 'nalgonda', name: 'Nalgonda' },
  { slug: 'bhuvanagiri', name: 'Bhuvanagiri' },
  { slug: 'bhongir', name: 'Bhongir' },
  { slug: 'shamirpet', name: 'Shamirpet' },
  { slug: 'shamshabad', name: 'Shamshabad' },
  { slug: 'rangareddy', name: 'Rangareddy' },
  { slug: 'vikarabad', name: 'Vikarabad' },
  { slug: 'narayanpet', name: 'Narayanpet' },
  { slug: 'mahabubnagar', name: 'Mahabubnagar' },
  { slug: 'nagarkurnool', name: 'Nagarkurnool' },
  { slug: 'wanaparthy', name: 'Wanaparthy' },
  { slug: 'gadwal', name: 'Gadwal' },

  // --- ANDHRA PRADESH: All 28 districts & major cities ---
  { slug: 'srikakulam', name: 'Srikakulam' },
  { slug: 'parvathipuram', name: 'Parvathipuram' },
  { slug: 'vizianagaram', name: 'Vizianagaram' },
  { slug: 'paderu', name: 'Paderu' },
  { slug: 'anakapalli', name: 'Anakapalli' },
  { slug: 'rampachodavaram', name: 'Rampachodavaram' },
  { slug: 'rajahmundry', name: 'Rajahmundry' },
  { slug: 'rajamahendravaram', name: 'Rajamahendravaram' },
  { slug: 'amalapuram', name: 'Amalapuram' },
  { slug: 'eluru', name: 'Eluru' },
  { slug: 'bhimavaram', name: 'Bhimavaram' },
  { slug: 'machilipatnam', name: 'Machilipatnam' },
  { slug: 'narasaraopeta', name: 'Narasaraopeta' },
  { slug: 'bapatla', name: 'Bapatla' },
  { slug: 'ongole', name: 'Ongole' },
  { slug: 'markapuram', name: 'Markapuram' },
  { slug: 'nandyal', name: 'Nandyal' },
  { slug: 'puttaparthi', name: 'Puttaparthi' },
  { slug: 'madanapalli', name: 'Madanapalli' },
  { slug: 'chittoor', name: 'Chittoor' },
];

/** City slug -> display name lookup */
export const CITY_MAP = new Map(CITIES.map((c) => [c.slug, c.name]));

/** Set of valid city slugs for fast lookup */
export const CITY_SLUGS = new Set(CITIES.map((c) => c.slug));

export function getCityName(slug: string): string {
  return CITY_MAP.get(slug) || slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
