// Complete Services Data - All 150+ Services from IndiaFilings

export interface Service {
  id: string;
  name: string;
  slug: string;
  category: string;
  subcategory?: string;
  description: string;
  basePrice: number;
  governmentFee: number;
  processingTime: string;
  requiredDocuments: string[];
  features: string[];
  benefits: string[];
  useCase: string;
  popular?: boolean;
}

export const serviceCategories = [
  { id: 'startup', name: 'Startup & Business Registration', icon: '🏢' },
  { id: 'registrations', name: 'Registrations & Licenses', icon: '📋' },
  { id: 'trademark', name: 'Trademark & IP', icon: '™️' },
  { id: 'gst', name: 'GST Services', icon: '💰' },
  { id: 'income-tax', name: 'Income Tax', icon: '📊' },
  { id: 'mca', name: 'MCA Compliance', icon: '⚖️' },
  { id: 'compliance', name: 'Compliance & Advisory', icon: '✅' },
];

export const services: Service[] = [
  // A. STARTUP & BUSINESS REGISTRATION (10 Services)
  {
    id: 'proprietorship-registration',
    name: 'Proprietorship Registration',
    slug: 'proprietorship-registration',
    category: 'startup',
    description: 'Register a sole proprietorship business with minimal compliance requirements.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-15 days',
    requiredDocuments: ['PAN', 'Aadhaar', 'Address proof', 'Bank account'],
    features: ['Simple registration', 'Minimal compliance', 'Quick processing'],
    benefits: ['Easy setup', 'Low cost', 'Minimal paperwork'],
    useCase: 'Individual entrepreneurs, small businesses',
  },
  {
    id: 'partnership-registration',
    name: 'Partnership Firm Registration',
    slug: 'partnership-registration',
    category: 'startup',
    description: 'Register a partnership business with multiple partners.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '10-20 days',
    requiredDocuments: ['Partnership deed', 'PAN of partners', 'Address proof'],
    features: ['Partnership deed', 'Multiple partners', 'Flexible structure'],
    benefits: ['Easy formation', 'Shared responsibility', 'Tax benefits'],
    useCase: 'Small businesses with 2+ partners',
  },
  {
    id: 'opc-registration',
    name: 'One Person Company (OPC) Registration',
    slug: 'opc-registration',
    category: 'startup',
    description: 'Register a company with single director and limited liability.',
    basePrice: 4999,
    governmentFee: 1500,
    processingTime: '15-25 days',
    requiredDocuments: ['DIN', 'DSC', 'MOA', 'AOA', 'Address proof'],
    features: ['Limited liability', 'Single member', 'Separate legal entity'],
    benefits: ['Limited liability', 'Corporate structure', 'Easy conversion'],
    useCase: 'Solo entrepreneurs wanting company structure',
  },
  {
    id: 'llp-registration',
    name: 'Limited Liability Partnership (LLP) Registration',
    slug: 'llp-registration',
    category: 'startup',
    description: 'Register an LLP with limited liability and flexible structure.',
    basePrice: 5999,
    governmentFee: 2000,
    processingTime: '15-30 days',
    requiredDocuments: ['LLP agreement', 'DIN', 'DSC', 'Address proof'],
    features: ['Limited liability', 'Flexible structure', 'Easy compliance'],
    benefits: ['Limited liability', 'Tax benefits', 'Less compliance'],
    useCase: 'Professional services, startups',
  },
  {
    id: 'private-limited-registration',
    name: 'Private Limited Company Registration',
    slug: 'private-limited-company-registration',
    category: 'startup',
    description: 'Register a private limited company with limited liability and separate legal entity.',
    basePrice: 5000,
    governmentFee: 1500,
    processingTime: '15-30 days',
    requiredDocuments: ['DIN', 'DSC', 'MOA', 'AOA', 'Address proof', 'Bank statements'],
    features: ['Limited liability', 'Separate legal entity', 'Easy fundraising'],
    benefits: ['Limited liability', 'Credibility', 'Easy to scale'],
    useCase: 'Most common business structure, scalable businesses',
    popular: true,
  },
  {
    id: 'section-8-company',
    name: 'Section 8 Company Registration',
    slug: 'section-8-company-registration',
    category: 'startup',
    description: 'Register a non-profit company for charitable purposes.',
    basePrice: 6999,
    governmentFee: 2000,
    processingTime: '30-45 days',
    requiredDocuments: ['MOA', 'AOA', 'License from Central Government'],
    features: ['No profit distribution', 'Charitable purpose', 'Tax exemption'],
    benefits: ['Tax benefits', 'Credibility', 'Legal protection'],
    useCase: 'NGOs, charitable organizations',
  },
  {
    id: 'trust-registration',
    name: 'Trust Registration',
    slug: 'trust-registration',
    category: 'startup',
    description: 'Register a trust for charitable purposes.',
    basePrice: 4999,
    governmentFee: 1000,
    processingTime: '20-30 days',
    requiredDocuments: ['Trust deed', 'Identity proof of trustees'],
    features: ['Trust deed', 'Trustees', 'Charitable objectives'],
    benefits: ['Tax benefits', 'Legal structure', 'Credibility'],
    useCase: 'Charitable trusts, religious organizations',
  },
  {
    id: 'public-limited-registration',
    name: 'Public Limited Company Registration',
    slug: 'public-limited-company-registration',
    category: 'startup',
    description: 'Register a public limited company that can raise public funds.',
    basePrice: 9999,
    governmentFee: 5000,
    processingTime: '30-45 days',
    requiredDocuments: ['MOA', 'AOA', 'DIN', 'DSC', 'Prospectus'],
    features: ['Can raise public funds', 'Listed companies', 'Higher credibility'],
    benefits: ['Public fundraising', 'High credibility', 'Growth potential'],
    useCase: 'Large businesses, public offerings',
  },
  {
    id: 'producer-company',
    name: 'Producer Company Registration',
    slug: 'producer-company-registration',
    category: 'startup',
    description: 'Register a producer company for agricultural producers.',
    basePrice: 5999,
    governmentFee: 2000,
    processingTime: '20-30 days',
    requiredDocuments: ['MOA', 'AOA', 'Producer details'],
    features: ['Agricultural producers', 'Cooperative structure', 'Tax benefits'],
    benefits: ['Tax benefits', 'Government support', 'Collective strength'],
    useCase: 'Agricultural cooperatives, farmer groups',
  },
  {
    id: 'indian-subsidiary',
    name: 'Indian Subsidiary Registration',
    slug: 'indian-subsidiary-registration',
    category: 'startup',
    description: 'Register a subsidiary of foreign company in India.',
    basePrice: 12999,
    governmentFee: 5000,
    processingTime: '30-45 days',
    requiredDocuments: ['Foreign company documents', 'Indian director details'],
    features: ['Foreign investment', 'FEMA compliance', 'Indian operations'],
    benefits: ['Market access', 'Legal structure', 'Compliance support'],
    useCase: 'Foreign companies entering India',
  },

  // B. REGISTRATIONS & LICENSES (27 Services) - Sample of key ones
  {
    id: 'startup-india',
    name: 'Startup India Registration',
    slug: 'startup-india-registration',
    category: 'registrations',
    description: 'Register with Startup India initiative for tax benefits and funding opportunities.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '15-20 days',
    requiredDocuments: ['Business registration', 'Innovation certificate'],
    features: ['Tax benefits', 'Funding opportunities', 'Easier compliance'],
    benefits: ['Tax exemption', 'Funding access', 'Government support'],
    useCase: 'New businesses with innovative ideas',
  },
  {
    id: 'trade-license',
    name: 'Trade License',
    slug: 'trade-license',
    category: 'registrations',
    description: 'License to carry out trade/business from Municipal Corporation.',
    basePrice: 1999,
    governmentFee: 500,
    processingTime: '7-15 days',
    requiredDocuments: ['Business registration', 'Address proof', 'Identity proof'],
    features: ['Municipal license', 'Business authorization', 'Legal compliance'],
    benefits: ['Legal authorization', 'Business credibility', 'Compliance'],
    useCase: 'All commercial businesses',
  },
  {
    id: 'fssai-registration',
    name: 'FSSAI Registration',
    slug: 'fssai-registration',
    category: 'registrations',
    description: 'Food Safety and Standards Authority registration for food businesses.',
    basePrice: 2499,
    governmentFee: 100,
    processingTime: '7-20 days',
    requiredDocuments: ['Business registration', 'Food safety plan', 'Address proof'],
    features: ['Food safety compliance', 'License types', 'Legal requirement'],
    benefits: ['Legal compliance', 'Consumer trust', 'Business authorization'],
    useCase: 'Food businesses',
    popular: true,
  },
  {
    id: 'fssai-license',
    name: 'FSSAI License',
    slug: 'fssai-license',
    category: 'registrations',
    description: 'FSSAI license for larger food businesses with higher turnover.',
    basePrice: 4999,
    governmentFee: 5000,
    processingTime: '15-30 days',
    requiredDocuments: ['Business registration', 'Food safety plan', 'Turnover proof'],
    features: ['Higher turnover', 'Central license', 'Comprehensive compliance'],
    benefits: ['Legal compliance', 'Business expansion', 'Consumer trust'],
    useCase: 'High turnover food businesses',
  },
  {
    id: 'iec-registration',
    name: 'Import Export Code (IEC)',
    slug: 'import-export-code',
    category: 'registrations',
    description: 'Code required for import/export businesses, issued by DGFT.',
    basePrice: 1999,
    governmentFee: 500,
    processingTime: '5-10 days',
    requiredDocuments: ['PAN', 'Bank account', 'Address proof'],
    features: ['DGFT registration', 'Import/Export authorization', 'Quick processing'],
    benefits: ['Import/Export authorization', 'International trade', 'Government support'],
    useCase: 'Import/Export businesses',
    popular: true,
  },
  {
    id: 'udyam-registration',
    name: 'Udyam Registration (MSME)',
    slug: 'udyam-registration',
    category: 'registrations',
    description: 'MSME registration replacing Udyog Aadhaar for government benefits.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '1-2 days',
    requiredDocuments: ['Aadhaar', 'PAN', 'Business details'],
    features: ['MSME benefits', 'Government support', 'Easy loans'],
    benefits: ['Government benefits', 'Easier loans', 'Tax benefits'],
    useCase: 'Micro, Small, Medium Enterprises',
    popular: true,
  },
  {
    id: 'dsc-registration',
    name: 'Digital Signature Certificate (DSC)',
    slug: 'digital-signature-certificate',
    category: 'registrations',
    description: 'Digital signature for online filings with MCA, GST, Income Tax.',
    basePrice: 1499,
    governmentFee: 0,
    processingTime: '2-5 days',
    requiredDocuments: ['Aadhaar', 'PAN', 'Photograph'],
    features: ['Class 2/Class 3', 'Online filings', 'Secure authentication'],
    benefits: ['Online filing', 'Secure transactions', 'Legal validity'],
    useCase: 'MCA filings, GST, Income Tax',
    popular: true,
  },
  {
    id: 'tan-registration',
    name: 'TAN Registration',
    slug: 'tan-registration',
    category: 'registrations',
    description: 'Tax Deduction Account Number registration for TDS deductors.',
    basePrice: 999,
    governmentFee: 55,
    processingTime: '5-7 days',
    requiredDocuments: ['PAN', 'Business registration', 'Address proof'],
    features: ['TDS compliance', 'Quick processing', 'Online application'],
    benefits: ['TDS compliance', 'Legal requirement', 'Easy process'],
    useCase: 'TDS deductors',
    popular: true,
  },
  {
    id: 'pf-registration',
    name: 'PF Registration',
    slug: 'pf-registration',
    category: 'registrations',
    description: 'Employee Provident Fund registration for businesses with 20+ employees.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-15 days',
    requiredDocuments: ['Business registration', 'Employee details', 'Bank account'],
    features: ['Employee benefits', 'Compliance', 'Government scheme'],
    benefits: ['Employee benefits', 'Legal compliance', 'Government support'],
    useCase: 'Businesses with 20+ employees',
  },
  {
    id: 'esi-registration',
    name: 'ESI Registration',
    slug: 'esi-registration',
    category: 'registrations',
    description: 'Employee State Insurance registration for employee health benefits.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-15 days',
    requiredDocuments: ['Business registration', 'Employee details', 'Bank account'],
    features: ['Health insurance', 'Employee benefits', 'Compliance'],
    benefits: ['Employee benefits', 'Health coverage', 'Legal compliance'],
    useCase: 'Businesses with 10+ employees',
  },
  {
    id: 'iso-registration',
    name: 'ISO Registration',
    slug: 'iso-registration',
    category: 'registrations',
    description: 'ISO certification for quality management systems.',
    basePrice: 9999,
    governmentFee: 0,
    processingTime: '30-60 days',
    requiredDocuments: ['Business registration', 'Quality manual', 'Process documents'],
    features: ['Quality certification', 'International standards', 'Business credibility'],
    benefits: ['Quality certification', 'Business credibility', 'International recognition'],
    useCase: 'Businesses seeking quality certification',
  },
  {
    id: '12a-registration',
    name: '12A Registration',
    slug: '12a-registration',
    category: 'registrations',
    description: 'Tax exemption registration for NGOs and charitable organizations.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '2-3 months',
    requiredDocuments: ['Trust/Society registration', 'MOA', 'Activity report'],
    features: ['Tax exemption', 'NGO benefits', 'Legal compliance'],
    benefits: ['Tax exemption', 'Donor benefits', 'Legal compliance'],
    useCase: 'NGOs, trusts, societies',
  },
  {
    id: '80g-registration',
    name: '80G Registration',
    slug: '80g-registration',
    category: 'registrations',
    description: 'Tax deduction registration for donors to charitable organizations.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '2-3 months',
    requiredDocuments: ['12A registration', 'Activity report', 'Financial statements'],
    features: ['Donor tax deduction', 'Charity benefits', 'Legal compliance'],
    benefits: ['Donor benefits', 'Tax deduction', 'Legal compliance'],
    useCase: 'Charitable organizations',
  },
  {
    id: 'fcra-registration',
    name: 'FCRA Registration',
    slug: 'fcra-registration',
    category: 'registrations',
    description: 'Foreign Contribution Regulation Act registration for NGOs receiving foreign funds.',
    basePrice: 9999,
    governmentFee: 0,
    processingTime: '2-3 months',
    requiredDocuments: ['NGO registration', 'Activity report', 'Foreign fund details'],
    features: ['Foreign funds', 'NGO compliance', 'Legal authorization'],
    benefits: ['Foreign funding', 'Legal compliance', 'International support'],
    useCase: 'NGOs receiving foreign funds',
  },
  {
    id: 'fire-license',
    name: 'Fire License',
    slug: 'fire-license',
    category: 'registrations',
    description: 'Fire safety license from Fire Department for commercial establishments.',
    basePrice: 2999,
    governmentFee: 1000,
    processingTime: '15-30 days',
    requiredDocuments: ['Building plan', 'Fire safety certificate', 'NOC'],
    features: ['Fire safety', 'Legal compliance', 'Safety standards'],
    benefits: ['Legal compliance', 'Safety standards', 'Business authorization'],
    useCase: 'Commercial establishments',
  },
  {
    id: 'shop-act-registration',
    name: 'Shop Act Registration',
    slug: 'shop-act-registration',
    category: 'registrations',
    description: 'Shops and Establishments Act registration from State Labor Department.',
    basePrice: 1499,
    governmentFee: 500,
    processingTime: '7-15 days',
    requiredDocuments: ['Business registration', 'Address proof', 'Employee details'],
    features: ['Labor compliance', 'State registration', 'Legal requirement'],
    benefits: ['Legal compliance', 'Employee protection', 'Business authorization'],
    useCase: 'All shops and commercial establishments',
  },
  {
    id: 'drug-license',
    name: 'Drug License',
    slug: 'drug-license',
    category: 'registrations',
    description: 'License for manufacturing/selling drugs from State Drug Controller.',
    basePrice: 4999,
    governmentFee: 2000,
    processingTime: '30-60 days',
    requiredDocuments: ['Business registration', 'Premises certificate', 'Qualified person'],
    features: ['Drug authorization', 'Manufacturing/Retail', 'Legal compliance'],
    benefits: ['Legal authorization', 'Business credibility', 'Compliance'],
    useCase: 'Pharmaceutical businesses',
  },
  {
    id: 'barcode-registration',
    name: 'Barcode Registration',
    slug: 'barcode-registration',
    category: 'registrations',
    description: 'Barcode registration from GS1 India for product identification.',
    basePrice: 9999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['Business registration', 'Product details'],
    features: ['Product identification', 'GS1 standard', 'International recognition'],
    benefits: ['Product tracking', 'Retail ready', 'International standards'],
    useCase: 'Product manufacturers',
  },
  {
    id: 'bis-registration',
    name: 'BIS Registration',
    slug: 'bis-registration',
    category: 'registrations',
    description: 'Bureau of Indian Standards registration for certain product categories.',
    basePrice: 9999,
    governmentFee: 5000,
    processingTime: '15-30 days',
    requiredDocuments: ['Product details', 'Test reports', 'Manufacturing details'],
    features: ['Quality standards', 'Product certification', 'Legal compliance'],
    benefits: ['Quality certification', 'Legal compliance', 'Consumer trust'],
    useCase: 'Product manufacturers (mandatory categories)',
  },
  {
    id: 'apeda-registration',
    name: 'APEDA Registration',
    slug: 'apeda-registration',
    category: 'registrations',
    description: 'Agricultural and Processed Food Products Export Development Authority registration.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['Business registration', 'Export details', 'Product details'],
    features: ['Export authorization', 'Agricultural products', 'Government support'],
    benefits: ['Export benefits', 'Government support', 'Market access'],
    useCase: 'Agricultural product exporters',
  },
  {
    id: 'professional-tax',
    name: 'Professional Tax Registration',
    slug: 'professional-tax-registration',
    category: 'registrations',
    description: 'State-level professional tax registration for professionals and businesses.',
    basePrice: 1499,
    governmentFee: 0,
    processingTime: '5-10 days',
    requiredDocuments: ['Business registration', 'PAN', 'Address proof'],
    features: ['State tax', 'Professional compliance', 'Legal requirement'],
    benefits: ['Legal compliance', 'State authorization', 'Business credibility'],
    useCase: 'Professionals and businesses (state-specific)',
  },
  {
    id: 'rmc-registration',
    name: 'RCMC Registration',
    slug: 'rmc-registration',
    category: 'registrations',
    description: 'Registration Cum Membership Certificate from export promotion councils.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['IEC', 'Export details', 'Business registration'],
    features: ['Export benefits', 'Council membership', 'Government support'],
    benefits: ['Export benefits', 'Government support', 'Market access'],
    useCase: 'Export businesses',
  },
  {
    id: 'halal-license',
    name: 'Halal License & Certification',
    slug: 'halal-license-certification',
    category: 'registrations',
    description: 'Halal certification for food products for export to Muslim countries.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['FSSAI license', 'Product details', 'Manufacturing process'],
    features: ['Halal certification', 'Export authorization', 'International standards'],
    benefits: ['Export authorization', 'Market access', 'Consumer trust'],
    useCase: 'Food product exporters to Muslim countries',
  },
  {
    id: 'icegate-registration',
    name: 'ICEGATE Registration',
    slug: 'icegate-registration',
    category: 'registrations',
    description: 'Indian Customs EDI Gateway registration for import/export businesses.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '5-10 days',
    requiredDocuments: ['IEC', 'Business registration'],
    features: ['Customs integration', 'Import/Export', 'Digital platform'],
    benefits: ['Digital platform', 'Faster processing', 'Government integration'],
    useCase: 'Import/Export businesses',
  },
  {
    id: 'lei-code',
    name: 'Legal Entity Identifier Code (LEI)',
    slug: 'legal-entity-identifier-code',
    category: 'registrations',
    description: 'Global identifier for legal entities for large transactions and financial reporting.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['Business registration', 'Financial details'],
    features: ['Global identifier', 'Financial reporting', 'International recognition'],
    benefits: ['International recognition', 'Financial compliance', 'Global standards'],
    useCase: 'Large transactions, financial reporting',
  },
  {
    id: 'darpan-registration',
    name: 'Darpan Registration',
    slug: 'darpan-registration',
    category: 'registrations',
    description: 'NGO Darpan registration for NGOs receiving government grants.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['NGO registration', 'Activity details'],
    features: ['Government grants', 'NGO benefits', 'Government platform'],
    benefits: ['Government grants', 'NGO benefits', 'Government support'],
    useCase: 'NGOs receiving government grants',
  },
  {
    id: 'certificate-incumbency',
    name: 'Certificate of Incumbency',
    slug: 'certificate-incumbency',
    category: 'registrations',
    description: 'Certificate showing current directors/officers for legal/banking purposes.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['Company registration', 'Director details'],
    features: ['Director certificate', 'Legal document', 'Banking requirement'],
    benefits: ['Legal document', 'Banking support', 'Business credibility'],
    useCase: 'Legal/banking purposes',
  },
  {
    id: 'tn-rera-agents',
    name: 'TN RERA Registration for Agents',
    slug: 'tn-rera-registration-agents',
    category: 'registrations',
    description: 'Tamil Nadu RERA registration for real estate agents.',
    basePrice: 2999,
    governmentFee: 1000,
    processingTime: '15-20 days',
    requiredDocuments: ['Real estate license', 'Address proof', 'Identity proof'],
    features: ['RERA compliance', 'Real estate authorization', 'Legal requirement'],
    benefits: ['Legal compliance', 'Real estate authorization', 'Business credibility'],
    useCase: 'Real estate agents in Tamil Nadu',
  },

  // C. TRADEMARK & IP (17 Services) - Key ones
  {
    id: 'trademark-registration',
    name: 'Trademark Registration',
    slug: 'trademark-registration',
    category: 'trademark',
    description: 'Register a trademark for brand protection across 45 classes of goods/services.',
    basePrice: 5999,
    governmentFee: 4500,
    processingTime: '6-12 months',
    requiredDocuments: ['Trademark name/logo', 'Class selection', 'Applicant details'],
    features: ['Brand protection', '45 classes', '10 years validity'],
    benefits: ['Brand protection', 'Legal rights', 'Business identity'],
    useCase: 'Brand protection, business identity',
    popular: true,
  },
  {
    id: 'trademark-objection',
    name: 'Trademark Objection Handling',
    slug: 'trademark-objection',
    category: 'trademark',
    description: 'Respond to trademark objections raised by trademark office.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '1-2 months',
    requiredDocuments: ['Objection notice', 'Supporting documents'],
    features: ['Objection response', 'Legal support', 'Expert guidance'],
    benefits: ['Objection resolution', 'Legal support', 'Trademark protection'],
    useCase: 'Address trademark office concerns',
  },
  {
    id: 'trademark-opposition',
    name: 'Trademark Opposition',
    slug: 'trademark-opposition',
    category: 'trademark',
    description: 'File opposition to similar trademark application to protect existing trademark.',
    basePrice: 6999,
    governmentFee: 2700,
    processingTime: '2-3 months',
    requiredDocuments: ['Similar trademark details', 'Supporting documents'],
    features: ['Opposition filing', 'Legal support', 'Trademark protection'],
    benefits: ['Trademark protection', 'Legal rights', 'Brand security'],
    useCase: 'Protect existing trademark',
  },
  {
    id: 'trademark-renewal',
    name: 'Trademark Renewal',
    slug: 'trademark-renewal',
    category: 'trademark',
    description: 'Renew trademark registration every 10 years to maintain protection.',
    basePrice: 4999,
    governmentFee: 9000,
    processingTime: '1-2 months',
    requiredDocuments: ['Trademark certificate', 'Renewal application'],
    features: ['10-year renewal', 'Continuous protection', 'Legal compliance'],
    benefits: ['Continuous protection', 'Legal compliance', 'Brand security'],
    useCase: 'Maintain trademark protection',
  },
  {
    id: 'copyright-registration',
    name: 'Copyright Registration',
    slug: 'copyright-registration',
    category: 'trademark',
    description: 'Register copyright for creative works including literary, artistic, musical, software.',
    basePrice: 3999,
    governmentFee: 500,
    processingTime: '2-3 months',
    requiredDocuments: ['Creative work', 'Author details', 'Work description'],
    features: ['Creative protection', 'Lifetime + 60 years', 'Multiple categories'],
    benefits: ['Creative protection', 'Legal rights', 'Business security'],
    useCase: 'Protect creative works',
  },
  {
    id: 'patent-registration',
    name: 'Patent Registration',
    slug: 'patent-registration',
    category: 'trademark',
    description: 'Register patent for inventions with 20 years validity from filing date.',
    basePrice: 29999,
    governmentFee: 15000,
    processingTime: '2-5 years',
    requiredDocuments: ['Invention details', 'Technical specifications', 'Drawings'],
    features: ['20 years protection', 'Invention rights', 'Legal protection'],
    benefits: ['Invention protection', 'Legal rights', 'Business advantage'],
    useCase: 'Protect inventions',
  },
  {
    id: 'design-registration',
    name: 'Design Registration',
    slug: 'design-registration',
    category: 'trademark',
    description: 'Register industrial design for product designs with 10 years validity.',
    basePrice: 5999,
    governmentFee: 2000,
    processingTime: '6-12 months',
    requiredDocuments: ['Design drawings', 'Product details', 'Design description'],
    features: ['10 years validity', 'Design protection', 'Renewable'],
    benefits: ['Design protection', 'Legal rights', 'Business security'],
    useCase: 'Protect product designs',
  },
  {
    id: 'logo-designing',
    name: 'Logo Designing',
    slug: 'logo-designing',
    category: 'trademark',
    description: 'Professional logo design services with brand guidelines.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '7-15 days',
    requiredDocuments: ['Brand requirements', 'Design preferences'],
    features: ['Professional design', 'Brand guidelines', 'Multiple revisions'],
    benefits: ['Brand identity', 'Professional design', 'Business credibility'],
    useCase: 'Brand identity creation',
  },

  // D. GST SERVICES (14 Services) - Key ones
  {
    id: 'gst-registration',
    name: 'GST Registration',
    slug: 'gst-registration',
    category: 'gst',
    description: 'Register for Goods and Services Tax (GST) for businesses with turnover > ₹20 lakhs.',
    basePrice: 1500,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['PAN', 'Business registration', 'Bank account', 'Address proof'],
    features: ['GST compliance', 'Quick processing', 'Online application'],
    benefits: ['GST compliance', 'Legal requirement', 'Business authorization'],
    useCase: 'Businesses with turnover > ₹20 lakhs',
    popular: true,
  },
  {
    id: 'gst-return-filing',
    name: 'GST Return Filing',
    slug: 'gst-return-filing',
    category: 'gst',
    description: 'Professional GST return filing service for GSTR-1, GSTR-3B, GSTR-9.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '1 day',
    requiredDocuments: ['GSTIN', 'Sales data', 'Purchase data'],
    features: ['Monthly/Quarterly filing', 'Accurate filing', 'Expert support'],
    benefits: ['GST compliance', 'Accurate filing', 'Expert support'],
    useCase: 'GST registered businesses',
    popular: true,
  },
  {
    id: 'gst-nil-return',
    name: 'GST NIL Return Filing',
    slug: 'gst-nil-return-filing',
    category: 'gst',
    description: 'File nil GST returns when there is no business activity.',
    basePrice: 499,
    governmentFee: 0,
    processingTime: '1 day',
    requiredDocuments: ['GSTIN'],
    features: ['Nil return', 'Quick filing', 'Compliance'],
    benefits: ['GST compliance', 'Legal requirement', 'Quick process'],
    useCase: 'Maintain GST compliance without activity',
  },
  {
    id: 'gst-amendment',
    name: 'GST Amendment',
    slug: 'gst-amendment',
    category: 'gst',
    description: 'Amend GST registration details like name, address, business details.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['GSTIN', 'Updated details', 'Supporting documents'],
    features: ['Details update', 'Quick processing', 'Online application'],
    benefits: ['Details update', 'Legal compliance', 'Quick process'],
    useCase: 'Update GST registration details',
  },
  {
    id: 'gst-revocation',
    name: 'GST Revocation',
    slug: 'gst-revocation',
    category: 'gst',
    description: 'Revoke cancelled GST registration if cancelled by mistake.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['GSTIN', 'Cancellation order', 'Justification'],
    features: ['Revocation', 'Legal support', 'Expert guidance'],
    benefits: ['Restore registration', 'Legal compliance', 'Business continuity'],
    useCase: 'Restore cancelled GST registration',
  },
  {
    id: 'gst-lut',
    name: 'GST LUT Form',
    slug: 'gst-lut-form',
    category: 'gst',
    description: 'Letter of Undertaking for exports to export without paying GST.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '2-3 days',
    requiredDocuments: ['GSTIN', 'Export details'],
    features: ['Export benefit', 'GST exemption', 'Quick processing'],
    benefits: ['Export benefit', 'GST exemption', 'Business advantage'],
    useCase: 'Export businesses',
  },
  {
    id: 'gst-notice',
    name: 'GST Notice Handling',
    slug: 'gst-notice-handling',
    category: 'gst',
    description: 'Respond to GST notices including scrutiny, assessment, demand notices.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['GST notice', 'Supporting documents'],
    features: ['Notice response', 'Legal support', 'Expert guidance'],
    benefits: ['Notice resolution', 'Legal compliance', 'Expert support'],
    useCase: 'Resolve GST issues',
  },
  {
    id: 'gstr-9',
    name: 'GST Annual Return Filing (GSTR-9)',
    slug: 'gst-annual-return-filing',
    category: 'gst',
    description: 'Annual GST return filing required annually for all GST registered businesses.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['GSTIN', 'Annual data', 'Financial statements'],
    features: ['Annual filing', 'Comprehensive return', 'Expert support'],
    benefits: ['Annual compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Annual GST compliance',
  },
  {
    id: 'gstr-10',
    name: 'GSTR-10 Filing',
    slug: 'gstr-10-filing',
    category: 'gst',
    description: 'Final return on cancellation of GST registration.',
    basePrice: 1499,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['GSTIN', 'Cancellation details'],
    features: ['Final return', 'Cancellation compliance', 'Expert support'],
    benefits: ['Cancellation compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Complete GST cancellation',
  },
  {
    id: 'gst-einvoicing',
    name: 'GST E-Invoicing Software',
    slug: 'gst-einvoicing-software',
    category: 'gst',
    description: 'Software for e-invoicing compliance for businesses with turnover > ₹5 crores.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['GSTIN', 'Business details'],
    features: ['E-invoicing', 'IRN generation', 'Compliance'],
    benefits: ['E-invoicing compliance', 'Legal requirement', 'Digital platform'],
    useCase: 'Businesses with turnover > ₹5 crores',
  },
  {
    id: 'gst-foreigner',
    name: 'GST Registration for Foreigners',
    slug: 'gst-registration-for-foreigners',
    category: 'gst',
    description: 'GST registration for non-resident businesses operating in India.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Foreign business documents', 'Indian operations details'],
    features: ['Foreign business', 'GST compliance', 'Expert support'],
    benefits: ['GST compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Foreign businesses operating in India',
  },
  {
    id: 'virtual-office-gstin',
    name: 'Virtual Office + GSTIN',
    slug: 'virtual-office-gstin',
    category: 'gst',
    description: 'Virtual office address for GST registration without physical office.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['Business details', 'Address proof'],
    features: ['Virtual office', 'GST registration', 'Business address'],
    benefits: ['GST registration', 'Business address', 'Cost effective'],
    useCase: 'GST registration without office',
  },

  // E. INCOME TAX SERVICES (10 Services)
  {
    id: 'income-tax-filing',
    name: 'Income Tax E-Filing',
    slug: 'income-tax-filing',
    category: 'income-tax',
    description: 'File income tax returns online for individuals and businesses.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '1-2 days',
    requiredDocuments: ['PAN', 'Aadhaar', 'Income details', 'Deduction details'],
    features: ['ITR filing', 'Multiple ITR forms', 'Expert support'],
    benefits: ['Tax compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Individuals and businesses',
    popular: true,
  },
  {
    id: 'business-tax-filing',
    name: 'Business Tax Filing',
    slug: 'business-tax-filing',
    category: 'income-tax',
    description: 'File tax returns for businesses including partnership, proprietorship, HUF.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['Business registration', 'Financial statements', 'Income details'],
    features: ['Business ITR', 'Expert support', 'Accurate filing'],
    benefits: ['Tax compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Businesses (Partnership, Proprietorship, HUF)',
  },
  {
    id: 'company-itr',
    name: 'Company ITR Filing',
    slug: 'company-itr-filing',
    category: 'income-tax',
    description: 'File income tax returns for companies using ITR-6 form.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['Company registration', 'Financial statements', 'Tax details'],
    features: ['Company ITR', 'ITR-6', 'Expert support'],
    benefits: ['Tax compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Companies',
  },
  {
    id: 'tds-return-filing',
    name: 'TDS Return Filing',
    slug: 'tds-return-filing',
    category: 'income-tax',
    description: 'File TDS returns quarterly using forms 24Q, 26Q, 27Q, 27EQ.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['TAN', 'TDS details', 'Deductor details'],
    features: ['Quarterly filing', 'Multiple forms', 'Expert support'],
    benefits: ['TDS compliance', 'Legal requirement', 'Expert support'],
    useCase: 'TDS deductors',
    popular: true,
  },
  {
    id: 'income-tax-notice',
    name: 'Income Tax Notice Handling',
    slug: 'income-tax-notice-handling',
    category: 'income-tax',
    description: 'Respond to income tax notices including scrutiny, assessment, demand notices.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['Tax notice', 'Supporting documents'],
    features: ['Notice response', 'Legal support', 'Expert guidance'],
    benefits: ['Notice resolution', 'Legal compliance', 'Expert support'],
    useCase: 'Resolve tax issues',
  },
  {
    id: 'itr-revised',
    name: 'Revised ITR Return (ITR-U)',
    slug: 'revised-itr-return',
    category: 'income-tax',
    description: 'File updated/revised ITR within 24 months from end of assessment year.',
    basePrice: 1499,
    governmentFee: 0,
    processingTime: '2-3 days',
    requiredDocuments: ['Original ITR', 'Correction details'],
    features: ['ITR correction', 'Updated return', 'Expert support'],
    benefits: ['ITR correction', 'Legal compliance', 'Expert support'],
    useCase: 'Correct errors in filed ITR',
  },
  {
    id: '15ca-15cb',
    name: '15CA - 15CB Filing',
    slug: '15ca-15cb-filing',
    category: 'income-tax',
    description: 'Forms for foreign remittance - 15CA (self-declaration) and 15CB (CA certificate).',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '1-2 days',
    requiredDocuments: ['Remittance details', 'Foreign transaction details'],
    features: ['Foreign remittance', 'CA certificate', 'Expert support'],
    benefits: ['Foreign remittance compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Foreign payments compliance',
  },

  // F. MCA COMPLIANCE (21 Services) - Key ones
  {
    id: 'company-compliance',
    name: 'Company Compliance',
    slug: 'company-compliance',
    category: 'mca',
    description: 'Annual compliance for companies including annual returns and financial statements.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['Company registration', 'Financial statements', 'Annual returns'],
    features: ['Annual compliance', 'Financial statements', 'Expert support'],
    benefits: ['MCA compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Maintain company status',
    popular: true,
  },
  {
    id: 'llp-compliance',
    name: 'LLP Compliance',
    slug: 'llp-compliance',
    category: 'mca',
    description: 'Annual compliance for LLPs including Form 11 and Form 8.',
    basePrice: 3999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['LLP registration', 'Financial statements', 'Annual returns'],
    features: ['Annual compliance', 'Form 11, Form 8', 'Expert support'],
    benefits: ['MCA compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Maintain LLP status',
    popular: true,
  },
  {
    id: 'opc-compliance',
    name: 'OPC Compliance',
    slug: 'opc-compliance',
    category: 'mca',
    description: 'Annual compliance for OPCs including annual returns and financial statements.',
    basePrice: 3999,
    governmentFee: 0,
    processingTime: '15-30 days',
    requiredDocuments: ['OPC registration', 'Financial statements', 'Annual returns'],
    features: ['Annual compliance', 'Financial statements', 'Expert support'],
    benefits: ['MCA compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Maintain OPC status',
  },
  {
    id: 'name-change-company',
    name: 'Name Change - Company',
    slug: 'name-change-company',
    category: 'mca',
    description: 'Change company name including name approval and MOA/AOA amendment.',
    basePrice: 4999,
    governmentFee: 1000,
    processingTime: '30-45 days',
    requiredDocuments: ['Company registration', 'New name', 'Board resolution'],
    features: ['Name approval', 'MOA/AOA amendment', 'Expert support'],
    benefits: ['Name change', 'Legal compliance', 'Expert support'],
    useCase: 'Rebranding, name correction',
  },
  {
    id: 'office-change',
    name: 'Registered Office Change',
    slug: 'registered-office-change',
    category: 'mca',
    description: 'Change registered office address - same state or different state.',
    basePrice: 2999,
    governmentFee: 500,
    processingTime: '15-30 days',
    requiredDocuments: ['Company registration', 'New address', 'Board resolution'],
    features: ['Address change', 'Same/Different state', 'Expert support'],
    benefits: ['Address update', 'Legal compliance', 'Expert support'],
    useCase: 'Relocation',
  },
  {
    id: 'din-ekyc',
    name: 'DIN eKYC Filing',
    slug: 'din-ekyc-filing',
    category: 'mca',
    description: 'Director Identification Number KYC required annually for all directors.',
    basePrice: 499,
    governmentFee: 0,
    processingTime: '1-2 days',
    requiredDocuments: ['DIN', 'Aadhaar', 'PAN'],
    features: ['Annual KYC', 'Quick processing', 'Online filing'],
    benefits: ['DIN maintenance', 'Legal compliance', 'Quick process'],
    useCase: 'Maintain active DIN',
    popular: true,
  },
  {
    id: 'din-reactivation',
    name: 'DIN Reactivation',
    slug: 'din-reactivation',
    category: 'mca',
    description: 'Reactivate deactivated DIN to restore director status.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['DIN', 'Deactivation details', 'Justification'],
    features: ['DIN reactivation', 'Legal support', 'Expert guidance'],
    benefits: ['Restore director status', 'Legal compliance', 'Expert support'],
    useCase: 'Restore director status',
  },
  {
    id: 'director-change',
    name: 'Director Change',
    slug: 'director-change',
    category: 'mca',
    description: 'Add or remove directors from company using DIR-12 form.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Director details', 'Board resolution'],
    features: ['Add/Remove director', 'DIR-12', 'Expert support'],
    benefits: ['Board changes', 'Legal compliance', 'Expert support'],
    useCase: 'Board changes',
    popular: true,
  },
  {
    id: 'remove-director',
    name: 'Remove Director',
    slug: 'remove-director',
    category: 'mca',
    description: 'Remove director from company using DIR-12 form.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Director details', 'Board resolution'],
    features: ['Remove director', 'DIR-12', 'Expert support'],
    benefits: ['Board changes', 'Legal compliance', 'Expert support'],
    useCase: 'Director resignation/removal',
  },
  {
    id: 'adt-1',
    name: 'ADT-1 Filing',
    slug: 'adt-1-filing',
    category: 'mca',
    description: 'Auditor appointment/change filing required when auditor changes.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Auditor details', 'Board resolution'],
    features: ['Auditor appointment', 'ADT-1', 'Expert support'],
    benefits: ['Auditor management', 'Legal compliance', 'Expert support'],
    useCase: 'Auditor management',
  },
  {
    id: 'dpt-3',
    name: 'DPT-3 Filing',
    slug: 'dpt-3-filing',
    category: 'mca',
    description: 'Return of deposits required annually for companies with deposits.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Deposit details', 'Financial statements'],
    features: ['Deposit return', 'Annual filing', 'Expert support'],
    benefits: ['Deposit compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Deposit compliance',
  },
  {
    id: 'llp-form-11',
    name: 'LLP Form 11 Filing',
    slug: 'llp-form-11-filing',
    category: 'mca',
    description: 'Annual return for LLP required annually.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['LLP registration', 'Annual details'],
    features: ['Annual return', 'Form 11', 'Expert support'],
    benefits: ['Annual compliance', 'Legal requirement', 'Expert support'],
    useCase: 'LLP annual compliance',
  },
  {
    id: 'dormant-status',
    name: 'Dormant Status Filing',
    slug: 'dormant-status-filing',
    category: 'mca',
    description: 'Convert company to dormant status when there is no business activity.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '15-20 days',
    requiredDocuments: ['Company registration', 'Inactivity proof'],
    features: ['Dormant status', 'Status conversion', 'Expert support'],
    benefits: ['Preserve company', 'Reduce compliance', 'Expert support'],
    useCase: 'Preserve company without operations',
  },
  {
    id: 'moa-amendment',
    name: 'MOA Amendment',
    slug: 'moa-amendment',
    category: 'mca',
    description: 'Amend Memorandum of Association when there is change in objects.',
    basePrice: 4999,
    governmentFee: 1000,
    processingTime: '30-45 days',
    requiredDocuments: ['Company registration', 'New objects', 'Board resolution'],
    features: ['MOA amendment', 'Object change', 'Expert support'],
    benefits: ['Object update', 'Legal compliance', 'Expert support'],
    useCase: 'Business expansion',
  },
  {
    id: 'aoa-amendment',
    name: 'AOA Amendment',
    slug: 'aoa-amendment',
    category: 'mca',
    description: 'Amend Articles of Association when there is change in internal rules.',
    basePrice: 2999,
    governmentFee: 500,
    processingTime: '15-20 days',
    requiredDocuments: ['Company registration', 'New rules', 'Board resolution'],
    features: ['AOA amendment', 'Rule change', 'Expert support'],
    benefits: ['Rule update', 'Legal compliance', 'Expert support'],
    useCase: 'Governance changes',
  },
  {
    id: 'capital-increase',
    name: 'Authorized Capital Increase',
    slug: 'authorized-capital-increase',
    category: 'mca',
    description: 'Increase authorized capital including MOA amendment and payment of fees.',
    basePrice: 3999,
    governmentFee: 1000,
    processingTime: '15-20 days',
    requiredDocuments: ['Company registration', 'Capital details', 'Board resolution'],
    features: ['Capital increase', 'MOA amendment', 'Expert support'],
    benefits: ['Capital expansion', 'Legal compliance', 'Expert support'],
    useCase: 'Capital expansion',
  },
  {
    id: 'share-transfer',
    name: 'Share Transfer',
    slug: 'share-transfer',
    category: 'mca',
    description: 'Transfer shares between parties using SH-4 and SH-7 forms.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Share details', 'Transfer agreement'],
    features: ['Share transfer', 'SH-4, SH-7', 'Expert support'],
    benefits: ['Ownership transfer', 'Legal compliance', 'Expert support'],
    useCase: 'Ownership transfer',
  },
  {
    id: 'demat-shares',
    name: 'Demat of Shares',
    slug: 'demat-shares',
    category: 'mca',
    description: 'Convert physical shares to demat format for listed companies.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '15-20 days',
    requiredDocuments: ['Company registration', 'Share certificates', 'Demat account'],
    features: ['Demat conversion', 'Modern format', 'Expert support'],
    benefits: ['Modern format', 'Easy transfer', 'Expert support'],
    useCase: 'Modernize shareholding',
  },
  {
    id: 'winding-up-llp',
    name: 'Winding Up - LLP',
    slug: 'winding-up-llp',
    category: 'mca',
    description: 'Close/wind up LLP either voluntarily or compulsorily.',
    basePrice: 9999,
    governmentFee: 0,
    processingTime: '3-6 months',
    requiredDocuments: ['LLP registration', 'Winding up resolution', 'Financial statements'],
    features: ['Winding up', 'Voluntary/Compulsory', 'Expert support'],
    benefits: ['Business closure', 'Legal compliance', 'Expert support'],
    useCase: 'Business closure',
  },
  {
    id: 'winding-up-company',
    name: 'Winding Up - Company',
    slug: 'winding-up-company',
    category: 'mca',
    description: 'Close/wind up company either voluntarily or compulsorily.',
    basePrice: 14999,
    governmentFee: 0,
    processingTime: '6-12 months',
    requiredDocuments: ['Company registration', 'Winding up resolution', 'Financial statements'],
    features: ['Winding up', 'Voluntary/Compulsory', 'Expert support'],
    benefits: ['Business closure', 'Legal compliance', 'Expert support'],
    useCase: 'Business closure',
  },
  {
    id: 'commencement-inc20a',
    name: 'Commencement (INC-20A)',
    slug: 'commencement-inc20a',
    category: 'mca',
    description: 'Declaration of commencement of business required within 180 days of incorporation.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['Company registration', 'Business commencement proof'],
    features: ['Commencement declaration', 'INC-20A', 'Expert support'],
    benefits: ['Business commencement', 'Legal compliance', 'Expert support'],
    useCase: 'Start business operations',
  },

  // G. COMPLIANCE & ADVISORY (13 Services) - Key ones
  {
    id: 'fdi-filing',
    name: 'FDI Filing with RBI',
    slug: 'fdi-filing-rbi',
    category: 'compliance',
    description: 'Foreign Direct Investment reporting to RBI using FC-GPR, FC-TRS forms.',
    basePrice: 4999,
    governmentFee: 0,
    processingTime: '5-7 days',
    requiredDocuments: ['Company registration', 'FDI details', 'Foreign investor details'],
    features: ['FDI reporting', 'RBI compliance', 'Expert support'],
    benefits: ['FDI compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Foreign investment compliance',
  },
  {
    id: 'fla-return',
    name: 'FLA Return Filing',
    slug: 'fla-return-filing',
    category: 'compliance',
    description: 'Foreign Liabilities and Assets return required annually for companies with foreign assets/liabilities.',
    basePrice: 3999,
    governmentFee: 0,
    processingTime: '7-10 days',
    requiredDocuments: ['Company registration', 'Foreign assets/liabilities details'],
    features: ['FLA return', 'Annual filing', 'Expert support'],
    benefits: ['FLA compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Foreign investment reporting',
  },
  {
    id: 'fssai-renewal',
    name: 'FSSAI Renewal',
    slug: 'fssai-renewal',
    category: 'compliance',
    description: 'Renew FSSAI license before expiry to maintain food license.',
    basePrice: 2999,
    governmentFee: 5000,
    processingTime: '7-15 days',
    requiredDocuments: ['FSSAI license', 'Renewal application'],
    features: ['License renewal', 'Before expiry', 'Expert support'],
    benefits: ['License maintenance', 'Legal compliance', 'Expert support'],
    useCase: 'Maintain food license',
  },
  {
    id: 'fssai-return',
    name: 'FSSAI Return Filing',
    slug: 'fssai-return-filing',
    category: 'compliance',
    description: 'File FSSAI annual returns required annually.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '3-5 days',
    requiredDocuments: ['FSSAI license', 'Annual details'],
    features: ['Annual return', 'FSSAI compliance', 'Expert support'],
    benefits: ['Annual compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Food license compliance',
  },
  {
    id: 'hr-payroll',
    name: 'HR & Payroll Processing',
    slug: 'hr-payroll-processing',
    category: 'compliance',
    description: 'Complete payroll management including salary processing, tax calculations, compliance.',
    basePrice: 99,
    governmentFee: 0,
    processingTime: 'Monthly',
    requiredDocuments: ['Employee details', 'Salary details', 'Tax details'],
    features: ['Payroll processing', 'Tax calculations', 'Compliance'],
    benefits: ['Payroll management', 'Tax compliance', 'Expert support'],
    useCase: 'Employee management',
    popular: true,
  },
  {
    id: 'pf-return',
    name: 'PF Return Filing',
    slug: 'pf-return-filing',
    category: 'compliance',
    description: 'File Provident Fund returns monthly using ECR and ECR Challan.',
    basePrice: 499,
    governmentFee: 0,
    processingTime: '2-3 days',
    requiredDocuments: ['PF registration', 'Employee details', 'Contribution details'],
    features: ['Monthly filing', 'ECR, ECR Challan', 'Expert support'],
    benefits: ['PF compliance', 'Legal requirement', 'Expert support'],
    useCase: 'PF compliance',
  },
  {
    id: 'esi-return',
    name: 'ESI Return Filing',
    slug: 'esi-return-filing',
    category: 'compliance',
    description: 'File ESI returns monthly for employee health benefits.',
    basePrice: 499,
    governmentFee: 0,
    processingTime: '2-3 days',
    requiredDocuments: ['ESI registration', 'Employee details', 'Contribution details'],
    features: ['Monthly filing', 'ESI compliance', 'Expert support'],
    benefits: ['ESI compliance', 'Legal requirement', 'Expert support'],
    useCase: 'ESI compliance',
  },
  {
    id: 'professional-tax-return',
    name: 'Professional Tax Return Filing',
    slug: 'professional-tax-return-filing',
    category: 'compliance',
    description: 'File professional tax returns monthly/quarterly (state-specific).',
    basePrice: 499,
    governmentFee: 0,
    processingTime: '2-3 days',
    requiredDocuments: ['Professional tax registration', 'Tax details'],
    features: ['Monthly/Quarterly filing', 'State-specific', 'Expert support'],
    benefits: ['Tax compliance', 'Legal requirement', 'Expert support'],
    useCase: 'Professional tax compliance',
  },
  {
    id: 'partnership-compliance',
    name: 'Partnership Compliance',
    slug: 'partnership-compliance',
    category: 'compliance',
    description: 'Annual compliance for partnerships including ITR filing and tax compliance.',
    basePrice: 2999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['Partnership registration', 'Financial statements', 'Tax details'],
    features: ['Annual compliance', 'ITR filing', 'Expert support'],
    benefits: ['Partnership maintenance', 'Legal compliance', 'Expert support'],
    useCase: 'Partnership maintenance',
  },
  {
    id: 'proprietorship-compliance',
    name: 'Proprietorship Compliance',
    slug: 'proprietorship-compliance',
    category: 'compliance',
    description: 'Annual compliance for proprietorships including ITR filing and tax compliance.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['Business details', 'Financial statements', 'Tax details'],
    features: ['Annual compliance', 'ITR filing', 'Expert support'],
    benefits: ['Proprietorship maintenance', 'Legal compliance', 'Expert support'],
    useCase: 'Proprietorship maintenance',
  },
  {
    id: 'bookkeeping',
    name: 'Bookkeeping Services',
    slug: 'bookkeeping-services',
    category: 'compliance',
    description: 'Professional bookkeeping including accounting and financial statements.',
    basePrice: 1999,
    governmentFee: 0,
    processingTime: 'Monthly/Quarterly',
    requiredDocuments: ['Business transactions', 'Financial documents'],
    features: ['Bookkeeping', 'Financial statements', 'Expert support'],
    benefits: ['Financial management', 'Accurate records', 'Expert support'],
    useCase: 'Financial management',
  },
  {
    id: 'ca-support',
    name: 'CA Support Services',
    slug: 'ca-support-services',
    category: 'compliance',
    description: 'Expert CA consultation and support for tax planning and compliance advice.',
    basePrice: 999,
    governmentFee: 0,
    processingTime: 'As needed',
    requiredDocuments: ['Business details', 'Compliance queries'],
    features: ['CA consultation', 'Tax planning', 'Compliance advice'],
    benefits: ['Expert guidance', 'Tax planning', 'Compliance support'],
    useCase: 'Professional guidance',
  },
  {
    id: 'business-plan',
    name: 'Business Plan Services',
    slug: 'business-plan-services',
    category: 'compliance',
    description: 'Professional business plan preparation with financial projections and market analysis.',
    basePrice: 9999,
    governmentFee: 0,
    processingTime: '10-15 days',
    requiredDocuments: ['Business idea', 'Market details', 'Financial projections'],
    features: ['Business plan', 'Financial projections', 'Market analysis'],
    benefits: ['Funding support', 'Business planning', 'Expert support'],
    useCase: 'Funding, planning',
  },
];

// Helper functions
export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug);
}

export function getServicesByCategory(category: string): Service[] {
  return services.filter(s => s.category === category);
}

export function getPopularServices(): Service[] {
  return services.filter(s => s.popular);
}

export function searchServices(query: string): Service[] {
  const lowerQuery = query.toLowerCase();
  return services.filter(s => 
    s.name.toLowerCase().includes(lowerQuery) ||
    s.description.toLowerCase().includes(lowerQuery) ||
    s.category.toLowerCase().includes(lowerQuery)
  );
}



